name: dart_amqp
description: >
  Dart AMQP client implementing protocol version 0.9.1
version: 0.1.4
author: Achilleas Anagnostopoulos
authors:
  - Achilleas Anagnostopoulos
  - GiKode <827266641@qq.com>
homepage: https://github.com/achilleasa/dart_amqp
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  logging: ^1.0.1
dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  http: ^0.13.3
  xml: ^5.1.1
  coveralls:
    git:
      url: https://github.com/AugustToko/coveralls.dart.git
  pedantic: ^1.11.0
  test_coverage:
    git:
      url: https://github.com/AugustToko/test-coverage.git
